# ***Q1***

In [ ]:
import torch

# Create a sample tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Reshape: Change the shape of the tensor
reshaped_tensor = tensor.view(3, 2)
print("Reshaped Tensor:")
print(reshaped_tensor)

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# View: Another way to change the shape of the tensor
viewed_tensor = tensor.view(3, -1)  # -1 means the size is inferred
print("\nViewed Tensor:")
print(viewed_tensor)


Viewed Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# Stack: Combine tensors along a new dimension
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack([tensor1, tensor2])
print("\nStacked Tensor:")
print(stacked_tensor)


Stacked Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Squeeze: Remove dimensions with size 1
tensor_with_dimension = tensor.view(1, 2, 3)
squeezed_tensor = tensor_with_dimension.squeeze()
print("\nSqueezed Tensor:")
print(squeezed_tensor)


Squeezed Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
unsqueezed_tensor = tensor.unsqueeze(dim=0)
print("\nUnsqueezed Tensor:")
print(unsqueezed_tensor)


Unsqueezed Tensor:
tensor([[[1, 2, 3],
         [4, 5, 6]]])


# ***Q2***

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]]])

# Original tensor shape: (2, 2, 3)
print("Original Tensor:")
print(tensor)

# Permute the dimensions (swap the first and last dimensions)
permuted_tensor = tensor.permute(2, 1, 0)
# New tensor shape: (3, 2, 2)
print("\nPermuted Tensor:")
print(permuted_tensor)

Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

Permuted Tensor:
tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]])


# ***Q3***

In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Accessing individual elements
element = tensor[1, 2]  # Row 1, Column 2 (zero-based indexing)
print("Single Element:")
print(element)

# Slicing along rows and columns
row_slice = tensor[0, :]  # Row 0, all columns
col_slice = tensor[:, 1]  # All rows, Column 1
print("\nRow Slice:")
print(row_slice)
print("\nColumn Slice:")
print(col_slice)

# Accessing a sub-tensor
sub_tensor = tensor[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2
print("\nSub-Tensor:")
print(sub_tensor)

# Using boolean indexing
bool_tensor = tensor > 5
filtered_tensor = tensor[bool_tensor]
print("\nBoolean Indexing:")
print(bool_tensor)
print(filtered_tensor)

Single Element:
tensor(6)

Row Slice:
tensor([1, 2, 3])

Column Slice:
tensor([2, 5, 8])

Sub-Tensor:
tensor([[2, 3],
        [5, 6]])

Boolean Indexing:
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([6, 7, 8, 9])


# ***Q4***

In [ ]:
import numpy as np

# Create a NumPy array
numpy_array = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Convert NumPy array to a PyTorch tensor
tensor_from_numpy = torch.tensor(numpy_array)
# or using torch.from_numpy()
# tensor_from_numpy = torch.from_numpy(numpy_array)

print("NumPy Array:")
print(numpy_array)

print("\nTensor from NumPy:")
print(tensor_from_numpy)

# Convert PyTorch tensor back to NumPy array
numpy_array_back = tensor_from_numpy.numpy()

print("\nNumPy Array from Tensor:")
print(numpy_array_back)

NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Tensor from NumPy:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NumPy Array from Tensor:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ***Q5***

In [ ]:
tensor_7x7 = torch.rand(7, 7)
print("Tensor of shape (7, 7):")
print(tensor_7x7)

Tensor of shape (7, 7):
tensor([[0.0831, 0.7872, 0.9447, 0.5242, 0.0629, 0.9500, 0.9045],
        [0.2276, 0.5808, 0.1727, 0.7363, 0.6632, 0.2656, 0.6841],
        [0.7749, 0.3350, 0.4347, 0.9749, 0.7178, 0.5184, 0.7945],
        [0.7010, 0.9801, 0.4195, 0.8187, 0.3978, 0.5532, 0.0428],
        [0.7353, 0.9744, 0.7713, 0.8660, 0.0777, 0.1504, 0.7922],
        [0.9752, 0.7355, 0.7767, 0.8961, 0.4503, 0.8446, 0.1730],
        [0.2193, 0.4530, 0.5191, 0.2629, 0.8086, 0.3218, 0.3369]])


# ***Q6***

# ***Q7***

In [ ]:
# Create random tensors on CPU
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# Check the device (should be 'cpu' by default)
print("Tensor 1 Device:", tensor1.device)
print("Tensor 2 Device:", tensor2.device)

# Send tensors to GPU (assuming a GPU is available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

# Check the device again (should be 'cuda' if GPU is available)
print("Tensor 1 Device (after moving to GPU):", tensor1.device)
print("Tensor 2 Device (after moving to GPU):", tensor2.device)

Tensor 1 Device: cpu
Tensor 2 Device: cpu
Tensor 1 Device (after moving to GPU): cpu
Tensor 2 Device (after moving to GPU): cpu


# ***Q8***

# ***Q9***

In [ ]:
# Find the minimum and maximum values

max_value_1 = torch.max(tensor1)
max_value_2 = torch.max(tensor2)

min_value_1 = torch.min(tensor1)
min_value_2 = torch.min(tensor2)

print("Tensor 1:")
print(tensor1)
print("\nMinimum Value:", min_value_1.item())
print("\nMaximum Value:", max_value_1.item())

print("\nTensor 2:")
print(tensor2)
print("\nMinimum Value:", min_value_2.item())
print("\nMaximum Value:", min_value_2.item())

Tensor 1:
tensor([[0.4581, 0.0811, 0.3775],
        [0.1335, 0.2948, 0.6716]])

Minimum Value: 0.08105307817459106

Maximum Value: 0.6716102957725525

Tensor 2:
tensor([[0.7907, 0.1570, 0.1473],
        [0.7525, 0.5946, 0.4888]])

Minimum Value: 0.14726245403289795

Maximum Value: 0.14726245403289795


# ***Q10***

In [ ]:
min_index_tensor1 = torch.argmin(tensor1)
max_index_tensor1 = torch.argmax(tensor1)

min_index_tensor2 = torch.argmin(tensor2)
max_index_tensor2 = torch.argmax(tensor2)

print("Tensor 1:")
print(tensor1)

print("\nIndex of Minimum Value in Tensor 1:", min_index_tensor1)
print("Index of Maximum Value in Tensor 1:", max_index_tensor1)

print("\nTensor 2:")
print(tensor2)

print("\nIndex of Minimum Value in Tensor 2:", min_index_tensor2)
print("Index of Maximum Value in Tensor 2:", max_index_tensor2)



Tensor 1:
tensor([[0.4581, 0.0811, 0.3775],
        [0.1335, 0.2948, 0.6716]])

Index of Minimum Value in Tensor 1: tensor(1)
Index of Maximum Value in Tensor 1: tensor(5)

Tensor 2:
tensor([[0.7907, 0.1570, 0.1473],
        [0.7525, 0.5946, 0.4888]])

Index of Minimum Value in Tensor 2: tensor(2)
Index of Maximum Value in Tensor 2: tensor(0)


# ***Q11***

In [ ]:
# Set the random seed for reproducibility
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor1 = torch.rand(1, 1, 1, 10)

# Remove all dimensions except the last one
tensor2 = tensor1.view(10)

# Print the first tensor and its shape
print("Tensor 1:")
print(tensor1)
print("Shape of Tensor 1:", tensor1.shape)

# Print the second tensor and its shape
print("\nTensor 2:")
print(tensor2)
print("Shape of Tensor 2:", tensor2.shape)

Tensor 1:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Tensor 1: torch.Size([1, 1, 1, 10])

Tensor 2:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Tensor 2: torch.Size([10])
